server:
  port: 10010 #服务端口
spring:
  application:
    name: gateway #指定服务名
#zuul:
#  routes:
#    hehe:
#      path: /user-service/**
#      url: http://127.0.0.1:8082
      #http://localhost:10010/user-service/user/1 转发
      #http:http://127.0.0.1:8082/user/1
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5   #5秒间隔获取服务列表
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    instance-id: ${spring.application.name}:${server.port}
#zuul:
#  routes:
#    haha:
#      path: /user-service/**
#      url: userService
    #http://localhost:10010/user-service/user/1 转发
    #http://userService/user/1
    #http:http://127.0.0.1:8082/user/1

#zuul:
#  routes:
#    userService: /user-service/**
    #http://localhost:10010/user-service/user/1 转发
    #http://userService/user/1
    #http:http://127.0.0.1:8082/user/1


    #customer-service: /customer-service/**

    #http://localhost:10010/customer-service/customer/1
    #http://customer-service/customer/1
    #http://localhost:8088/customer/1


#zuul:
#  routes:
#    userService: /user-service/**
#  ignored-services:
#    - customer-service



#zuul:
#  prefix: /api
#  routes:
#    userService: /user-service/**
#  ignored-services:
#    - customer-service
    #http://localhost:10010/api/user-service/user/1 转发
    #http://userService/user/1
    #http:http://127.0.0.1:8082/user/1

#zuul:
#  routes:
#    userService:
#      path: /user/**
#      serviceId: userService
#      strip-prefix: false #不进行截取
#  ignored-services:
#    - customer-service
 #http://localhost:10010/user/1
 #http://userService/user/1
 #http:http://127.0.0.1:8082/user/1


zuul:
  prefix: /api
  routes:
    userService:
      path: /user/**
      serviceId: userService
      strip-prefix: false #不进行截取
  ignored-services:
    - customer-service
  #http://localhost:10010/api/user/1
  #过滤 如果有权限 转发 如果没有权限 不转发 FilterZuul
  #http://userService/user/1
  #http:http://127.0.0.1:8082/user/1

#day0315
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 6000 # 熔断超时时长：6000ms
#day0315
ribbon:
  ConnectionTimeOut: 500 # 连接超时时间(ms)
  ReadTimeOut: 4000 # 通信超时时间(ms)
  MaxAutoRetriesNextServer: 2 # 同一服务不同实例的重试次数