server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/day01
    username: root
    password: 123456
  application:
    name: userService
mybatis:
  type-aliases-package: com.bigdata.user.pojo

eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5   #5秒间隔获取服务列表
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    instance-id: ${spring.application.name}:${server.port}
