server:
  port: 8088
spring:
  application:
    name: customer-service #应用名称
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5   #5秒间隔获取服务列表
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 # 设置hystrix的超时时间为3000ms
feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能
ribbon:
  ConnectionTimeOut: 500 #建立连接时间
  ReadTimeOut: 2000 #feign中ribbon配置